version: '2'
services:
  sqldb:
    image: postgres:10
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/sqldb:/var/lib/postgres/data
    networks:
      app_net:
        ipv4_address: 173.17.0.2
  memcached:
    image: memcached:1.5.20
    networks:
      app_net:
        ipv4_address: 173.17.0.3
  app:
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=sqldb
      - DATABASE_URL=postgres://postgres@sqldb
      - MEMCACHED_HOST=memcached
      - SMTP_HOSTNAME=localhost
      - SMTP_PORT=443
      - SMTP_USERNAME=foo
      - SMTP_PASSWORD=bar
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./data/bundle:/bundle
    ports:
      - "3000:3000"
    links:
      - sqldb
      - memcached
    networks:
      app_net:
        ipv4_address: 173.17.0.6

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 173.17.0.0/24
          gateway: 173.17.0.1