FROM node:16-alpine

EXPOSE 5000

RUN mkdir -p /app
WORKDIR app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN addgroup -S appgroup && adduser -S appuser -G appgroup && npm install && REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL} npm run build && npm install -g serve

USER appuser

ENTRYPOINT ["serve", "-s", "-l", "5000", "build"]
