version: '3.8'
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  backend:
    image: devops-with-docker-backend
    ports:
      - 8080:8080
    links:
      - redis
      - postgres
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  frontend:
    image: devops-with-docker-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres

