FROM node:16

EXPOSE 5000

RUN mkdir -p /app
WORKDIR app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm install
RUN REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL} npm run build
RUN npm install -g serve
ENTRYPOINT ["serve", "-s", "-l", "5000", "build"]
