FROM golang:1.16

RUN mkdir -p /app
WORKDIR /app

COPY . .

RUN go build

ARG PORT=8080
ENV REQUEST_ORIGIN=http://localhost

RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

EXPOSE ${PORT}

ENTRYPOINT ["./server"]
