version: '3'

services:
  web1:
    image: nginx:latest
    ports:
      - 8081:80

  web2:
    image: nginx:latest
    ports:
      - 8082:80

  web3:
    image: nginx:latest
    ports:
      - 8083:80
